[metadata]
name = "my_lora2"
version = "1.0"
author = ""
train_type = "anima-lora"
description = ""

[data]
model_train_type = "anima-lora"
pretrained_model_name_or_path = "./sd-models/model.safetensors"
vae = ""
qwen3 = ""
train_data_dir = "./train"
resume = ""
resolution = "1024,1024"
enable_bucket = true
bucket_no_upscale = true
min_bucket_reso = 256
max_bucket_reso = 2048
bucket_reso_steps = 64
network_module = "networks.lora_anima"
network_train_unet_only = false
network_train_text_encoder_only = true
network_dim = 32
network_alpha = 32
network_weights = ""
network_dropout = 0
scale_weight_norms = ""
lycoris_algo = "lora"
conv_dim = ""
conv_alpha = ""
lokr_factor = ""
use_cp = false
use_scalar = false
decompose_both = false
full_matrix = false
train_norm = false
rank_dropout = ""
module_dropout = ""
dropout = ""
dora_wd = false
block_size = 4
constraint = 0
rescaled = false
bypass_mode = false
rs_lora = false
max_train_epochs = 10
train_batch_size = 1
gradient_accumulation_steps = 1
gradient_checkpointing = false
seed = 1337
mixed_precision = "bf16"
timestep_sampling = "sigmoid"
sigmoid_scale = 1
discrete_flow_shift = 1
weighting_scheme = "uniform"
logit_mean = 0
logit_std = 1
mode_scale = 1.29
min_timestep = ""
max_timestep = ""
optimizer_type = "vendor.emo_optimizer.emosens.EmoSens"
learning_rate = "0.1"
unet_lr = "1e-4"
text_encoder_lr = "1e-5"
self_attn_lr = ""
cross_attn_lr = ""
mlp_lr = ""
mod_lr = ""
llm_adapter_lr = ""
lr_scheduler = "constant"
lr_warmup_steps = 0
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
max_grad_norm = 0
weight_decay = 0.01
stopcoef = 0.04
prodigy_d_coef = "1.0"
prodigy_d0 = ""
betas = ""
eps = ""
came_weight_decouple = true
came_fixed_decay = false
came_clip_threshold = 1
came_ams_bound = false
came_eps1 = ""
came_eps2 = ""
loss_type = "l2"
huber_schedule = "snr"
huber_c = 0.1
huber_scale = 1
min_snr_gamma = ""
noise_offset = ""
caption_extension = ".txt"
max_token_length = "75"
qwen3_max_token_length = 512
t5_max_token_length = 512
shuffle_caption = true
keep_tokens = 0
weighted_captions = false
caption_dropout_rate = ""
caption_dropout_every_n_epochs = ""
caption_tag_dropout_rate = ""
attn_mode = "torch"
split_attn = false
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = false
cache_text_encoder_outputs_to_disk = false
lowram = false
vae_chunk_size = ""
vae_disable_cache = false
blocks_to_swap = ""
torch_compile = false
dynamo_backend = "inductor"
output_name = "my_lora"
output_dir = "./output"
save_model_as = "safetensors"
save_precision = "fp16"
save_every_n_epochs = 2
save_every_n_steps = ""
save_state = false
save_last_n_epochs_state = ""
logging_dir = "./logs"
log_with = "tensorboard"
enable_preview = false
positive_prompts = ""
negative_prompts = ""
sample_sampler = "euler_a"
sample_every_n_epochs = 2
sample_cfg = 7
sample_width = 512
sample_height = 512
sample_seed = 2333
sample_steps = 24
model_type = "chroma"
apply_t5_attn_mask = true
model_prediction_type = "raw"
guidance_scale = 0
